# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: uthantvicentin 
email: uthantvicentin@unir.br 
description: "Esse é um blog minimalista criado para aprender como funciona essa ferramenta linda que é o Jekyll."
baseurl: ""
url: ""
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
permalink: /:title/
